# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from . import types
from . import stream_types


type_map = {

    "types.FidelityScore": types.FidelityScore,
    "stream_types.FidelityScore": stream_types.FidelityScore,

    "types.Ingredient": types.Ingredient,
    "stream_types.Ingredient": stream_types.Ingredient,

    "types.InventoryParsingResult": types.InventoryParsingResult,
    "stream_types.InventoryParsingResult": stream_types.InventoryParsingResult,

    "types.Recipe": types.Recipe,
    "stream_types.Recipe": stream_types.Recipe,

    "types.RecipeIngredient": types.RecipeIngredient,
    "stream_types.RecipeIngredient": stream_types.RecipeIngredient,

    "types.RecipePitch": types.RecipePitch,
    "stream_types.RecipePitch": stream_types.RecipePitch,


}