# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions

import baml_py

from . import stream_types, types
from .runtime import DoNotUseDirectlyCallManager, BamlCallOptions

class LlmResponseParser:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def ExtractIngredients(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.InventoryParsingResult:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ExtractIngredients", llm_response=llm_response, mode="request")
        return typing.cast(types.InventoryParsingResult, result)

    def FleshOutRecipe(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.CompleteRecipe:
        result = self.__options.merge_options(baml_options).parse_response(function_name="FleshOutRecipe", llm_response=llm_response, mode="request")
        return typing.cast(types.CompleteRecipe, result)

    def GenerateRecipePitches(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> typing.List["types.RecipePitch"]:
        result = self.__options.merge_options(baml_options).parse_response(function_name="GenerateRecipePitches", llm_response=llm_response, mode="request")
        return typing.cast(typing.List["types.RecipePitch"], result)

    

class LlmStreamParser:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def ExtractIngredients(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.InventoryParsingResult:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ExtractIngredients", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.InventoryParsingResult, result)

    def FleshOutRecipe(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.CompleteRecipe:
        result = self.__options.merge_options(baml_options).parse_response(function_name="FleshOutRecipe", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.CompleteRecipe, result)

    def GenerateRecipePitches(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> typing.List["stream_types.RecipePitch"]:
        result = self.__options.merge_options(baml_options).parse_response(function_name="GenerateRecipePitches", llm_response=llm_response, mode="stream")
        return typing.cast(typing.List["stream_types.RecipePitch"], result)

    