# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from pydantic import BaseModel, ConfigDict

import baml_py

from . import types

StreamStateValueT = typing.TypeVar('StreamStateValueT')
class StreamState(BaseModel, typing.Generic[StreamStateValueT]):
    value: StreamStateValueT
    state: typing_extensions.Literal["Pending", "Incomplete", "Complete"]
# #########################################################################
# Generated classes (2)
# #########################################################################

class Ingredient(BaseModel):
    name: typing.Optional[str] = None
    quantity: typing.Optional[float] = None
    unit: typing.Optional[str] = None
    priority: typing.Optional[str] = None
    portion_size: typing.Optional[str] = None

class InventoryParsingResult(BaseModel):
    ingredients: typing.List["Ingredient"]
    parsing_notes: typing.Optional[str] = None

# #########################################################################
# Generated type aliases (0)
# #########################################################################
