# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from pydantic import BaseModel, ConfigDict

import baml_py

from . import types

StreamStateValueT = typing.TypeVar('StreamStateValueT')
class StreamState(BaseModel, typing.Generic[StreamStateValueT]):
    value: StreamStateValueT
    state: typing_extensions.Literal["Pending", "Incomplete", "Complete"]
# #########################################################################
# Generated classes (6)
# #########################################################################

class CompleteRecipe(BaseModel):
    name: typing.Optional[str] = None
    description: typing.Optional[str] = None
    ingredients: typing.List["RecipeIngredient"]
    instructions: typing.List[str]
    active_time_minutes: typing.Optional[int] = None
    total_time_minutes: typing.Optional[int] = None
    servings: typing.Optional[int] = None
    notes: typing.Optional[str] = None

class Ingredient(BaseModel):
    name: typing.Optional[str] = None
    quantity: typing.Optional[float] = None
    unit: typing.Optional[str] = None
    priority: typing.Optional[types.Priority] = None
    portion_size: typing.Optional[str] = None

class InventoryParsingResult(BaseModel):
    ingredients: typing.List["Ingredient"]
    parsing_notes: typing.Optional[str] = None

class PitchIngredient(BaseModel):
    name: typing.Optional[str] = None
    quantity: typing.Optional[float] = None
    unit: typing.Optional[str] = None

class RecipeIngredient(BaseModel):
    name: typing.Optional[str] = None
    quantity: typing.Optional[str] = None
    unit: typing.Optional[str] = None
    preparation: typing.Optional[str] = None
    notes: typing.Optional[str] = None
    purchase_likelihood: typing.Optional[float] = None

class RecipePitch(BaseModel):
    name: typing.Optional[str] = None
    blurb: typing.Optional[str] = None
    why_make_this: typing.Optional[str] = None
    inventory_ingredients: typing.List["PitchIngredient"]
    active_time_minutes: typing.Optional[int] = None

# #########################################################################
# Generated type aliases (0)
# #########################################################################
