# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from . import types
from . import stream_types


type_map = {

    "types.Ingredient": types.Ingredient,
    "stream_types.Ingredient": stream_types.Ingredient,

    "types.InventoryParsingResult": types.InventoryParsingResult,
    "stream_types.InventoryParsingResult": stream_types.InventoryParsingResult,


    "types.Priority": types.Priority,

}