# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from enum import Enum


from pydantic import BaseModel, ConfigDict


import baml_py

CheckT = typing_extensions.TypeVar('CheckT')
CheckName = typing_extensions.TypeVar('CheckName', bound=str)

class Check(BaseModel):
    name: str
    expression: str
    status: str
class Checked(BaseModel, typing.Generic[CheckT, CheckName]):
    value: CheckT
    checks: typing.Dict[CheckName, Check]

def get_checks(checks: typing.Dict[CheckName, Check]) -> typing.List[Check]:
    return list(checks.values())

def all_succeeded(checks: typing.Dict[CheckName, Check]) -> bool:
    return all(check.status == "succeeded" for check in get_checks(checks))
# #########################################################################
# Generated enums (1)
# #########################################################################

class Priority(str, Enum):
    Low = "Low"
    Medium = "Medium"
    High = "High"
    Urgent = "Urgent"

# #########################################################################
# Generated classes (7)
# #########################################################################

class CompleteRecipe(BaseModel):
    name: str
    description: str
    ingredients: typing.List["RecipeIngredient"]
    instructions: typing.List[str]
    active_time_minutes: int
    total_time_minutes: int
    servings: int
    notes: typing.Optional[str] = None

class Ingredient(BaseModel):
    name: str
    quantity: float
    unit: str
    priority: Priority
    portion_size: typing.Optional[str] = None

class InventoryIngredient(BaseModel):
    name: str
    quantity: float
    unit: str
    priority: str

class InventoryParsingResult(BaseModel):
    ingredients: typing.List["Ingredient"]
    parsing_notes: typing.Optional[str] = None

class PitchIngredient(BaseModel):
    name: str
    quantity: float
    unit: str

class RecipeIngredient(BaseModel):
    name: str
    quantity: str
    unit: str
    preparation: typing.Optional[str] = None
    notes: typing.Optional[str] = None
    purchase_likelihood: float

class RecipePitch(BaseModel):
    name: str
    blurb: str
    why_make_this: str
    inventory_ingredients: typing.List["PitchIngredient"]
    active_time_minutes: int

# #########################################################################
# Generated type aliases (0)
# #########################################################################
