[project]
name = "backend"
version = "0.1.0"
description = "Backend for Harvest Hound"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pydantic>=2.11.7",
    "fastapi>=0.115.6",
    "uvicorn>=0.30.6",
    "baml-py>=0.62.0",
    "datamodel-code-generator[http]>=0.31.2",
]

[dependency-groups]
dev = ["pyright>=1.1.402"]
lint = ["mypy>=1.16.1"]
test = ["pytest>=8.4.1", "httpx>=0.27.0"]

[tool.ruff]
line-length = 88

[tool.ruff.lint]
select = ["E", "F", "I", "C90"]

[tool.ruff.lint.per-file-ignores]
"app/infrastructure/baml_client/**/*" = ["ALL"]

[tool.black]
exclude = "app/infrastructure/baml_client/"

[tool.mypy]
python_version = "3.12"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
disallow_untyped_decorators = true
no_implicit_optional = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_no_return = true
warn_unreachable = true
strict_equality = true

[[tool.mypy.overrides]]
module = "app.infrastructure.baml_client.*"
ignore_missing_imports = true
ignore_errors = true
