"""add_soft_delete_to_inventory_item

Revision ID: 9500142437fe
Revises: 8b03e34c7d86
Create Date: 2025-12-12 19:26:41.748805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9500142437fe'
down_revision: Union[str, Sequence[str], None] = '8b03e34c7d86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventoryitem', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inventoryitem', 'deleted_at')
    # ### end Alembic commands ###
