"""add pitch lifecycle fields

Revision ID: 9db1bb82b857
Revises: 9500142437fe
Create Date: 2025-12-13 13:18:30.508104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9db1bb82b857'
down_revision: Union[str, Sequence[str], None] = '9500142437fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add columns separately to avoid circular dependency issues in SQLite
    with op.batch_alter_table('pitch', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recipe_id', sa.Uuid(), nullable=True))

    with op.batch_alter_table('pitch', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rejected', sa.Boolean(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pitch', schema=None) as batch_op:
        batch_op.drop_column('rejected')

    with op.batch_alter_table('pitch', schema=None) as batch_op:
        batch_op.drop_column('recipe_id')
    # ### end Alembic commands ###
